### ISSUE TITLE
Uncaught Error: `initialFocus` refers to no known node

### ISSUE THREAD

**Issue by Armaldio** [joeattardi/emoji-button#117]
When attempting to show the emoji picker, I'm encountering this issue.

Here is all the code related to the emoji picker

```js
import {
    EmojiButton
} from '@joeattardi/emoji-button';

const picker = new EmojiButton({
    position: 'top-end',
    style: 'twemoji',
});

picker.on('emoji', selection => {
    $timeout(() => {
        $scope.textToSend += selection.emoji;
        $scope.$textarea.focus();
    });
});

const $trigger = angular.element('#emoji-trigger');

$trigger.on('click', () => picker.showPicker($trigger.get(0)));
```

**Comment by joeattardi** [comment]
Based on the code, I'm guessing this is an AngularJS app? I've never tried Emoji Button in an Angular app before. I could try to take a closer look if you could set up a codesandbox demonstrating the issue.

**Comment by Armaldio** [comment]
Yes it is.
Not sure it’s related to angular since it worked at some point then I updated and it broke
I also tried using vanilla js functions 

I cant be sure when because I haven’t tried every release

I’m gonna setup a sandbox anyway

**Comment by Armaldio** [comment]
Well, I have the same code in a sandbox and it's working
Any help regarding the origin of the error ?

**Comment by joeattardi** [comment]
I'm pretty sure that error is coming from the `focus-trap` library that I'm using. The relevant code is [here](https://github.com/joeattardi/emoji-button/blob/master/src/index.ts#L169-L175). I'm not sure what the problem is. You haven't disabled autofocus on the search, so it should be trying to focus the search field. For some reason it can't find that element.

If you can reproduce this error somewhere I'd be happy to take a look but off the top of my head I'm not sure what's going on here. You're using pretty basic code for showing the emoji picker, nothing fancy there. It could be some AngularJS weirdness that I'm not aware of.

**Comment by Armaldio** [comment]
So, after digging focus-trap, I found out that the error came from the fact that it could not find element with class `.emoji-picker__search`.
I delayed the EmojiButton creation to after the page was fully loaded (because I suspect Angular.js to override somehow the DOM added by this library if it is added before angular itself is loaded)

For reference, here is the code I have now:

```js
		angular.element(document).ready(() => {
			const picker = new EmojiButton({
				position: 'top-end',
				style: 'twemoji',
			});
			picker.on('emoji', selection => {
				...
			});
			const $trigger = document.querySelector('#emoji-trigger');

			$trigger.addEventListener('click', () => picker.togglePicker($trigger));
		});
```

Thanks a lot!
