### ISSUE TITLE
[Question] Usage inside input or textarea

### ISSUE THREAD

**Issue by collimarco** [joeattardi/emoji-button#137]
I can't find any example of usage of this library for adding emoji support to an input or textarea.

Is it suited for that? Is there any documentation about this topic?

For example, how can you insert the selected emoji in the current position (and not simply at the end of the text in the textarea)?

**Comment by adamcoulombe** [comment]
Its a good question, and would be good if there were some more examples like this available. Here is my version that uses `selectionStart` to remember the cursor position when the emoji button is clicked, so that it can insert it back into the correct spot:

https://codepen.io/adamcoulombe/pen/eYBjvyq

**Comment by joeattardi** [comment]
That is outside the scope of this library. This library provides you with the emoji picker, and fires an event when an emoji is selected. What you do with the selected emoji is up to you.

**Comment by cyberfly** [comment]
@collimarco use this library https://github.com/fregante/text-field-edit
