### ISSUE TITLE
Flags not working - When a flag is selected, instead of image, country code is showing

### ISSUE THREAD

**Issue by Sreejithga** [joeattardi/emoji-button#147]
Hello,

Please can you help me fix this issue. Everything with emoji-button works great except for flags. When I select a flag, it shows its country code in the reference element instead of the image. Even in the emoji-button website its so. Kindly guide on how to fix this issue.

![image](https://user-images.githubusercontent.com/53110553/115580784-76851180-a2d8-11eb-97f5-b91bf67dccb6.png)

Thanks in advance !

**Comment by joeattardi** [comment]
What operating system are you running?

Emoji support varies between operating systems. In particular, if you are running Windows, that might explain why you are seeing the two letters. Microsoft intentionally does not support country flag emojis on any version of Windows.

There are other potential causes too, but it is most likely _not_ an Emoji Button issue, unfortunately. 

Can you go to this link, and see if the flags are rendering with just two letter codes there as well?

https://emojipedia.org/flag-andorra/

I believe you could get around this issue by using the Twemoji emojis, actually. Twemoji provides the emojis as image files that will look the same on all platforms (SVG files, I believe). So as long as your platform supports SVG - which I'm sure it does in 2021 😄 - you should see the flag emojis for the different countries. Take a look at the Twemoji documentation for Emoji Button and try that example: https://emoji-button.js.org/docs/styles/

Native emojis are rendered differently on different operating systems. It is up to the OS vendor to provide glyphs (images) for the various emoji Unicode sequences.

If you're at all curious about how it works in more detail, I wrote [a blog post](https://joeattardi.codes/how-emojis-work) a while back that explains some of it.

Anyway, I hope this helps. I will close the issue for now since there really isn't anything that can be done about it from my end. Feel free to re-open or open another one if you have any other issues.

Thank you!
