### ISSUE TITLE
Support for Emoji 13?

### ISSUE THREAD

**Issue by CircuitSacul** [joeattardi/emoji-button#150]
Are there any plans to support [emoji 13](https://emojipedia.org/emoji-13.0/)?

**Comment by LiviuAMDi** [comment]
+1 from me

**Comment by joeattardi** [comment]
Hi, sorry for the late response on this.

So Emoji 13 is actually already supported, it looks like I need to update the documentation. Currently it defaults to Emoji 12.1, though given Emoji 13 has been out since last January, I think it's safe to make that the default now.

I will try to get to that tonight or tomorrow, in the meantime you can pass `emojiVersion: '13.0'` to the options in the constructor and you should be good to go.

**Comment by joeattardi** [comment]
Will be included in v5.
