### ISSUE TITLE
Jest 27+ / Jest encountered an unexpected token

### ISSUE THREAD

**Issue by alg-ext** [joeattardi/emoji-button#179]
Hello, 

Versions: 
- Angular 13
- @joeattardi/emoji-button ^4.6.2
- Jest 27.5.0

I run my tests with Jest 27+ and I have a runtime error.
It's an Angular and nx project.

I tried several Jest configurations but it does not work.

have you ever had this error ?

![Capture d’écran 2022-02-08 à 11 12 40](https://user-images.githubusercontent.com/98875497/152966285-a81ada14-7105-4fb0-87b7-5b277c628ca9.png)

**Comment by joeattardi** [comment]
Jest throws this error when it encounters what it thinks is invalid JS code.

Is it just the emoji-button code that's causing this?

Can you share some example code?

**Comment by alg-ext** [comment]
I tried with a new angular project with basic config for jest. 
The tests pass at first and as soon as I add the lib in a component the tests fail.
Test passes if I remove the creation of the object.

![image](https://user-images.githubusercontent.com/98875497/153615791-2db71007-78e0-41ec-bff3-23ad219b8af2.png)

**Comment by joeattardi** [comment]
Is there any additional output that tells you what the unexpected token is? If we know that we can hopefully figure out how the config needs to be adjusted.

**Comment by joeattardi** [comment]
Or if you want, can you create a small GitHub repo reproducing the error?

**Comment by alg-ext** [comment]
Here is a basic project with Angular / Jest and @joeattardi/emoji-button where I got the mentioned error with jest.
https://github.com/alg-ext/angular-jest-emoji-button

**Comment by joeattardi** [comment]
Great, thanks! I see the problem now.

Currently, Emoji Button is _only_ distributed as an ES Module. To run in Jest, Jest needs to transform it into a format that Jest (really, Node.js) understands.

It's not a great fix but you need to extend the `transformIgnorePattern` defined by the Angular preset so that `@joeattardi/emoji-button` is no longer ignored - then it will be transformed and Jest can understand it.

Change your `jest.config.js` so it looks like this:

```
const presets = require('jest-preset-angular/presets');

module.exports = {
  preset: "jest-preset-angular",
  setupFilesAfterEnv: ["<rootDir>/setupJest.ts"],
  transformIgnorePatterns: [
    `${presets.defaults.transformIgnorePatterns[0]}(?!@joeattardi/emoji-button)`
  ]
};
```

This will fix your unexpected token but then you'll have a new problem - jsdom, which Jest uses, does not support `IntersectionObserver` so you'll need to mock it otherwise your tests will fail saying `IntersectionObserver` is not defined.

Before you can fix _this_ there's one other issue with your `tsconfig.spec.json` file. 

In the `types` array defined from lines 6-8, remove "jasmine" and add "jest", otherwise TypeScript will fail when you use any of the jest-specific things (`test`, `jest`, etc.)

Once you've done that, open `setupJest.ts` and add this line:

```javascript
window.IntersectionObserver = jest.fn();
```

This mocks the `IntersectionObserver`. Once you make these changes, running `npm test` should result in passing tests.

Sorry for the difficulty here. I am close to finishing the new major rewrite of Emoji Button (version 5) and this is something I will keep in mind. For example, I could provide a commonjs bundle for use in tests so you don't have to transpile the ESM inside `node_modules`.

Hope this helps!

**Comment by alg-ext** [comment]
It works !!

For the `tsconfig.spec.json` It was a demonstration project for you, I had not configured in detail. 
I replicated your solution in my real more complex project and it works fine.

Thank you for your detailed explanations.

**Comment by tarcCar** [comment]
I am with same error but with react, anyone has the solution?

**Comment by joeattardi** [comment]
It's likely the same underlying issue. Jest can't understand ES modules and this is the cause of the error - assuming you're using Jest. 

You'll need to make a similar change to the transform ignore pattern so that TypeScript (or Babel or whatever you're using) will transpile the Emoji Button module. 

Depending on what your test is doing you could always simply mock the @joeattardi/emoji-button module within Jest to provide a simple mock implementation. 

This is probably a better solution actually. Your tests shouldn't be testing the functionality of Emoji Button itself but how your component interacts with it. Mocking the module lets you easily test the different scenarios you expect.
