### ISSUE TITLE
Emoji is adding in the end of the string

### ISSUE THREAD

**Issue by Shah-ali** [joeattardi/emoji-button#29]
Emoji is adding in the end of the string.
Current functionality -
An keeps a doctor away 🍎

Expected functionality -
An 🍎 keeps a doctor away

**Comment by joeattardi** [comment]
That's just because the demo app is a naive simplified app. You can handle the emoji any way you like in your app.

The insertion of the emoji into the text field is just the demo behavior. It's not done by the Emoji Button library. Here's what happens: When a user clicks an emoji, the picker fires an `emoji` event. You need to listen for that event then you can do whatever you want with the emoji - append it to the end of a text field, insert it at the current cursor position, log it to the console, POST it to a remote server, etc. It's totally flexible and up to you.

**Comment by Shah-ali** [comment]
Thanks for the reply @joeattardi. I have done that by using cursor position.
