### ISSUE TITLE
Error displaying windows 7 emojis

### ISSUE THREAD

**Issue by wagnerfillio** [joeattardi/emoji-button#35]
Hello, thanks for this plugin!
I have only one doubt!
How can I use it on older systems? For example, I'm trying to view on windows 7

![image](https://user-images.githubusercontent.com/22008303/75559806-deb4cc00-5a22-11ea-8531-edae49d4e01d.png)

**Comment by joeattardi** [comment]
Unlike some other emoji pickers, Emoji Button uses the system emoji font. This means that older operating systems won't have good emoji support.

In your case, on Windows 7, Microsoft actually released an update to the "Segoe UI Symbol" font that might improve the compatibility. See here: https://www.istartedsomething.com/20120818/microsoft-backports-windows-8-emoji-for-segoe-ui-symbol-to-windows-7/

If that doesn't help, I'm afraid there isn't much else that can be done. Some emoji pickers use sprite sheets to display their emojis, however this picker is meant as a native emoji picker.

Hope this helps.

**Comment by wagnerfillio** [comment]
Can you use twemoji as an add-on at some point?

**Comment by joeattardi** [comment]
I'd be happy to do that if I can think of a good way to integrate it.

**Comment by joeattardi** [comment]
You know, I just took a look at the twemoji api - it should be doable, since it seems to parse the emoji Unicode sequences, so it should be pretty easy to integrate into the picker.

The question is, what happens when the user picks one of the twemoji emojis? This library does not include an emoji textarea or anything so where would it insert the twemoji image? 

I suppose I could leave that as the responsibility of the developer - use twemoji in their main project and handle the insertion of the emoji image somehow.

This is a great idea!

**Comment by joeattardi** [comment]
I just created #36 to track this enhancement. Feel free to star and/or follow this project to get updates on it!

**Comment by joeattardi** [comment]
Good news! I have just released version 2.12.0 which includes Twemoji support.
