### ISSUE TITLE
Question about "smiling face" emoji

### ISSUE THREAD

**Issue by MorningSleeper** [joeattardi/emoji-button#47]
Hi, do you know why when I select a colored emoji to be inserted into a form field most show the exact colored emoji in the form field while at least one named "smiling face" shows a colorless version? My script inserts the comma before it and it occurs whether that is done or not. I tried in latest Chrome and Firefox. I have `<meta charset="UTF-8">` in documents head section. I included a screen capture that loops twice below.

![example](https://user-images.githubusercontent.com/8920632/79702792-3bcb4200-825c-11ea-807e-61b9902c81ca.gif)

**Comment by joeattardi** [comment]
I ran into this early on and it drove me crazy, I couldn't figure it out. Luckily, the fix is easy. You need to use the system emoji font on your text area.  This should cover it for all major platforms:

```css
font-family: "Segoe UI Emoji", "Segoe UI Symbol", "Segoe UI", "Apple Color Emoji", "Twemoji Mozilla", "Noto Color Emoji", "EmojiOne Color", "Android Emoji";
```

Give that a try, and feel free to close the issue if that fixes your problem - which I think it probably will!

**Comment by MorningSleeper** [comment]
That fixed it, thanks!
