### ISSUE TITLE
Colon emojis

### ISSUE THREAD

**Issue by MorettoM** [joeattardi/emoji-button#55]
Hi, I would like to know if there is already a feature to use emojis with **:colon:** or if there is good advice as how to integrate this.
thanks

**Comment by joeattardi** [comment]
This isn't supported in Emoji Button, unfortunately. The emoji data from Unicode that it parses does not include the colon short codes. There is a package, node-emoji (https://www.npmjs.com/package/node-emoji), which maps these short codes to emoji characters and back again, but I'm not sure if it works in the browser.

I probably won't add support for this because it would involve a lot of data about the short code mappings, and this library is already pretty large with the basic emoji data 😄 

Hope this helps.
