### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Justsnoopy30** [joeattardi/emoji-button#64]
I've noticed that all the events are blocking and synchronous. Could we possibly change to handle loading the emoji picker, loading the emoji's, etc. asynchronously and non-blocking?

**Comment by bhargavweb** [comment]
> I've noticed that all the events are blocking and synchronous. Could we possibly change to handle loading the emoji picker, loading the emoji's, etc. asynchronously and non-blocking?

Even I am facing performance issues. Its taking 3-4 seconds for the popup to display after clicking on the button.

**Comment by joeattardi** [comment]
I am working on addressing this. Basically, I am pre-creating the picker in the background as soon as the `EmojiButton` instance is created, then simply setting it visible when the button is clicked. It also will reuse the same instance instead of destroying and re-creating all those DOM elements. Hopefully that will help.

**Comment by joeattardi** [comment]
The performance seems better now. I'm going to close this for now; feel free to re-open after 4.0.0 is released if you still see performance issues.
