### ISSUE TITLE
Dropdown when typing : like emojiOnearea picker

### ISSUE THREAD

**Issue by jicihome** [joeattardi/emoji-button#65]
I would like to see this feature so when we type : it show a dropdown to select emoji based on text search entered after exactly like here, if I type :smile this give 😄

**Comment by joeattardi** [comment]
Hi, thanks for the suggestion. You actually aren't the first person to request this.

However, the problem is, the emoji data source that I use from Unicode does not contain the short-code names. There are libraries that map from the short-code names to the emojis, I suggest you look into that.

The other thing about this request is that it doesn't really fit the picker. The text field where you type is not part of the library, the only piece that is the library is the emoji picker itself. 

If I were to add this functionality I would have to provide an emoji text field component as well, which I feel is outside the scope of the library.
