### ISSUE TITLE
Demo is broken: missing and overlapped emojis

### ISSUE THREAD

**Issue by callshark** [joeattardi/emoji-button#68]
In the demo at https://emoji-button.js.org/, there are two issues:

1) There are some emojis which are missing, so they show up as a blank square.

2) There are some emojis which randomly appear inside the list/grid (in the gutter areas).

Chrome Version 83.0.4103.106 (Official Build) (64-bit) - Mac OS X 10.14.6:
<img width="479" alt="Screen Shot 2020-07-10 at 1 29 02 PM" src="https://user-images.githubusercontent.com/59974950/87187108-3f49f480-c2b2-11ea-8ee7-750dc2e41782.png">

Safari Version 13.1.1 (14609.2.9.1.3) - Mac OS X 10.14.6:
<img width="471" alt="Screen Shot 2020-07-10 at 1 31 49 PM" src="https://user-images.githubusercontent.com/59974950/87187121-4244e500-c2b2-11ea-9702-6813d78af814.png">

I'm able to reproduce both issues when using emoji-button in my own application too, so it appears to be a general bug.

Here's an example which shows some emojis clearly appear outside the normal grid:

<img width="2524" alt="Screen Shot 2020-07-10 at 1 37 02 PM" src="https://user-images.githubusercontent.com/59974950/87187267-80da9f80-c2b2-11ea-9172-0c0ac8019178.png">

**Comment by joeattardi** [comment]
I'm guessing this is due to your OS version. Some of the emojis that aren't rendering properly in your screenshots were added in macOS Catalina. Since you appear to be running Mojave (10.14), my guess is that those emojis are not supported by the OS. 

Emoji Button has an `emojiVersion` option that lets you specify an older emoji version if desired; see https://github.com/joeattardi/emoji-button#options.

Unfortunately, I don't know of a way to programmatically test if a given emoji is supported by the current OS. Otherwise I would have added something like that to hide emojis that aren't supported.

I'm afraid here your only options are to upgrade your OS or use an older Emoji version.

Hope this helps.

**Comment by callshark** [comment]
Thanks! When I set `emojiVersion` to `11.0`, it did indeed solve the problem.

Would it make sense to use a version other than `12.1` as the default, so users are more likely to see supported emojis?
