### ISSUE TITLE
Remove button

### ISSUE THREAD

**Issue by sowenjub** [joeattardi/emoji-button#69]
What do you think of adding a button/event to clear the selection?

This is how Notion handles hit for instance, but since there's only one button to add, it could probably be at the right end of the search field instead of above it.
![Notion Picker](https://imgur.com/dpuPDI1.png)

**Comment by joeattardi** [comment]
Hi, thanks for the suggestion! I'm not sure what you mean though - what selection would the button be cleaing?

**Comment by sowenjub** [comment]
I show a button with a placeholder (gray smiley face) that has no emoji to begin with.
When clicked, it shows the emoji picker, and the placeholder is replaced with the emoji.
But once there is an emoji, there's no going back. I can't click the emoji and unset it.

**Comment by joeattardi** [comment]
Sounds like a really specific use case. I can't think of a lot of other use cases where that would make sense. This emoji picker is more meant for picking emojis to insert into a text field of sorts, not to set a selection on a single emoji. 

What I *might* be able to do is add a generic extension point where you can specify an element to be included in the picker, in a way allowing you to write little "plugins" for the picker. You could then create your "remove" button and set it as a plugin. This is a really good idea actually, there are probably other use cases for folks adding their own buttons or functionality to the picker.

I can brainstorm on this a little more, but would be a good enhancement.

I'm currently working on finalizing and testing for the upcoming 4.0.0 release. If I have time I can try to include something in there, otherwise it might be later, like 4.1.0 or something.

Thanks again for the suggestion!

**Comment by sowenjub** [comment]
I can't point to other use cases than Notion.so and my app, so maybe it is really specific indeed.
Slack doesn't allow you to replace your emoji, if you click on it, it clears the value, which is what I'll be doing in the meantime.

The extension point would be great. In any case, thanks for this component!

**Comment by qortex** [comment]
Here is my use case, it also falls in the "notion-like" use case. I use it as an avatar picker for the user.

![image](https://user-images.githubusercontent.com/37897072/87774625-14691e80-c825-11ea-845a-2e0a87c103be.png)

**Comment by joeattardi** [comment]
I have implemented a hook for plugins. The example plugin I did was your use case - a button to remove a selected emoji. Watch for it in the 4.0.0 release coming soon.

**Comment by sowenjub** [comment]
Well, that was fast. Thanks a lot @joeattardi !

**Comment by joeattardi** [comment]
No problem! I hope to have 4.0.0 out this week, unless there's unforeseen problems. Will have an all-new website with better documentation too!
