### ISSUE TITLE
And how can i solve npm ERR! missing script : develop problem

### ISSUE THREAD

**Issue by themkynetwork** [joeattardi/emoji-button#79]

**Comment by joeattardi** [comment]
I think I might know the issue here.

Are you running `npm run develop` from the root of the repository?

`npm run develop` should be run from the `site` subdirectory. Make sure to do an `npm install` in there as well.

So:

```
cd site
npm install
npm run develop
```

`npm run develop` should be run in the `site` subdirectory, `npm run build:watch` should be run from the repository root.

**Comment by themkynetwork** [comment]
how can i go back to root repo

**Comment by joeattardi** [comment]
What I mean by the root of the repository is the directory you cloned the repository into. In my case that's `/Users/joe/code/emoji-button`. From that directory, you want to run `npm run build:watch`. 

Then, there is a subdirectory called `site`. Again, in my case that's `/Users/joe/code/emoji-button/site`. What you should do is open *another* terminal window or tab, and go to *that* directory. From that directory, you can run `npm run develop`.

At this point you should have two terminal windows. One is running `npm run build:watch` from the root directory, and the other is running `npm run develop` from the `site` directory. 

Then you should be up and running.
